version: "3.9"

services:
  spring_app:
    container_name: app-mereles
    build: .
    image: app-mereles:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mereles_db:5432/ignaDB
      - SPRING_DATASOURCE_USERNAME=igna01
      - SPRING_DATASOURCE_PASSWORD=igna2001
    depends_on:
      - mereles_db
    volumes:
      - imagenes:/app/imagenes  # Volumen para almacenar imágenes

  mereles_db:
    container_name: mereles_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=igna01
      - POSTGRES_PASSWORD=igna2001
      - POSTGRES_DB=ignaDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Volumen para persistir los datos de PostgreSQL

volumes:
  imagenes:  # Volumen para imágenes
  db_data:   # Volumen para PostgreSQL
